version: 3.0.0.{build}

init:
- cmd: echo Project - %APPVEYOR_PROJECT_NAME%
- cmd: echo Worker image - %APPVEYOR_BUILD_WORKER_IMAGE%
- cmd: echo Branch - %APPVEYOR_REPO_BRANCH%
- cmd: echo Author - %APPVEYOR_REPO_COMMIT_AUTHOR%
- cmd: echo Commit - %APPVEYOR_REPO_COMMIT%
#- cmd: echo (%APPVEYOR_REPO_COMMIT_MESSAGE%)
#- cmd: echo (%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%)
- cmd: echo Platform - %PLATFORM%
- cmd: echo Configuration - %CONFIGURATION%
- cmd: IF %APPVEYOR_REPO_BRANCH%=='develop' (SET APPVEYOR_BUILD_VERSION=%APPVEYOR_BUILD_VERSION%-beta)
- cmd: echo Version - %APPVEYOR_BUILD_VERSION%
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

nuget:
  account_feed: false
  project_feed: false

install:
- cmd: C:\projects\platform-components\scripts\restore_nugets.bat

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
platform: x64
environment:
  nuget_user:
    secure: kWtlS49bKmP0IFXmdvDHmxGI8mS0xQGrwiJoco9nYtA=
  nuget_password:
    secure: Pzvx2CQjxp8eCBP+nFI2eg==
  appveyor_rdp_password:
    secure: Pzvx2CQjxp8eCBP+nFI2eg==
configuration:
  - Debug
  - Release

# skip branch build if there is an active pull request
skip_branch_with_pr: true

build:
  parallel: true
  project: .\src\platform-components.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: quiet

after_build:
  - cmd: nuget pack C:\projects\platform-components\src\Spectre.Service\Spectre.Service.csproj -IncludeReferencedProjects
  - cmd: nuget pack C:\projects\platform-components\src\Spectre.Mvvm\Spectre.Mvvm.csproj -IncludeReferencedProjects


artifacts:
- path: .\src\Spectre.DataValidatorApp\bin\$(platform)\$(configuration)
  name: DataValidator-$(configuration)
- path: .\docs\*.pdf
  name: Manuals
- path: '**\*.nupkg'
  name: NugetPackages-$(configuration)

deploy:
  # push all packed apps to GitHub releases
  - provider: GitHub
    release: platform-components-v$(appveyor_build_version)
    auth_token:
      secure: dQadz+smqtuxpigZ/LmrUKyA0uVZ5kgljKntyoHEdobTycbeMywbfmiJtZPNcOQ2
    artifact: /.*\.zip/
    draft: true
  # push all NuGet-s to GitHub releases
  - provider: GitHub
    release: platform-components-v$(appveyor_build_version)
    auth_token:
      secure: dQadz+smqtuxpigZ/LmrUKyA0uVZ5kgljKntyoHEdobTycbeMywbfmiJtZPNcOQ2
    artifact: /.*\^(packages).*.nupkg/
    prerelease: false
    draft: true
  # push all manuals to GitHub releases
  - provider: GitHub
    release: platform-components-v$(appveyor_build_version)
    auth_token:
      secure: dQadz+smqtuxpigZ/LmrUKyA0uVZ5kgljKntyoHEdobTycbeMywbfmiJtZPNcOQ2
    artifact: Manuals
    on:
      branch:
        - master
        - develop
      configuration: Release
    draft: true
  # push all NuGet-s to our feed
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/gmrukwa-xfn7vhwq20u6
    api_key:
      secure: t8FO9T5wMCmRVqjBKL+8u6wmF+EPGJ8NDgcZoH7hbk4=
    skip_symbols: false
    symbol_server: https://ci.appveyor.com/nuget/gmrukwa-xfn7vhwq20u6
    artifact: /.*\.nupkg/
    on:
      branch:
        - master
        - develop
      configuration: Release

on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
# this publishes to Continuous Integration channel in Glip
- provider: Webhook
  url:
    secure: V16hjhyXfcLNyhNUih9v1Lb4wDly5r6CNNufciMrvllwt0m0rkguf6o4DY7pbdKia/vJGmErvQLdEW0MkzqsAhLWiPY7+Z6qvzFjweP8xNg=
  method: POST
  content_type: application/json
  body: >-
    {
      "icon": "https://www.appveyor.com/assets/img/appveyor-logo-256.png",
      "activity": "AppVeyor for platform-components",
      "title": "Build {{buildVersion}} **{{#failed}}failed{{/failed}}{{#passed}}passed{{/passed}}** in {{duration}}",
      "body": "{{#isPullRequest}}Pull request: [#{{pullRequestId}}](https://github.com/spectre-team/spectre/pull/{{pullRequestId}})\n{{/isPullRequest}}Branch: [{{branch}}](https://github.com/spectre-team/spectre/tree/{{branch}})\nCommit: [{{commitId}} {{commitMessage}}](https://github.com/spectre-team/spectre/commit/{{commitId}})\nAuthor: {{commitAuthor}}\n[Build details]({{buildUrl}})"
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
